Sodatea  docs vite plugin
niksy/node-stdlib-browser pull request #22
Opened 2022-09-26 12:06 UTC by milahu

continue #17  

todo: test "dont build in test" in CI. maybe add "npm run build && " before the test command

2023-05-05 18:39 UTC, happysalada commented
@niksy what do you think about this PR ?

2023-05-07 08:46 UTC, niksy commented
@happysalada I’ve left some comments for @milahu to review. When that’s done, I will merge PR.

2023-05-07 13:35 UTC, milahu commented
where?

maybe you forgot to click "finish your review"

2023-05-08 08:21 UTC, niksy requested changes

2023-05-08 10:20 UTC, milahu commented on test/index.js
> -			await execa('npm', ['run', 'build'], { cwd });
this is better for my workflow:

- build
- test
- modify the JS files produced by build
- test
- modify
- test

which is faster than running build on every test

> todo: test "dont build in test" in CI. maybe add "npm run build && " before the test command

2023-05-08 10:21 UTC, milahu commented on example/esm/vite-plugin/vite.config.mjs
> +/* defineConfig: what is the benefit?
yes. defineConfig has the advantage of intellisense for vite config

2023-05-08 10:28 UTC, milahu commented
abandoned (sorry)

2023-05-08 18:41 UTC, niksy commented on test/index.js
> -			await execa('npm', ['run', 'build'], { cwd });
Don’t know what you mean by "your workflow", but this is the flow where you want to have proper test output. If you forget to run `npm run build` you will get wrong results.

2023-09-22 06:55 UTC, niksy commented
Added reference to documentation.

2023-09-22 06:55 UTC, closed without merging